### PR TITLE
remove superfluous slashes 

### PR DESCRIPTION
**Pull request by diggy**

### CODE REVIEW

**Comment by panique** [comment]
This breaks the application. Test your stuff please!

**Comment by diggy** [comment]
`APP` is defined with a trailing slash (`DIRECTORY_SEPARATOR`), so the PR shouldn't break things (I tested locally), compare usage elsewhere e.g. `require APP . 'controller/home.php';` in the `Application` class constructor.

**Comment by d1maz** [comment]
Yeah diggy is right, just tested and it works.

**Comment by panique** [comment]
Supercool, gentlemen! Thanks! I'll merge this in the next days.

**Pull request merged**
