### PR TITLE
Add example nginx config to README

### LINKED ISSUE #142: [documentation request] NGINX rewrite rule
Heyyy,

if somebody is running MINI on nginx, could you please post your nginx rewrite rules ? Please note that index.php is now in /public folder, not in root folder anymore.

FYI: Rewrite-rules from the old php-mvc:
https://github.com/panique/mini/issues/55
https://github.com/panique/mini/pull/60

### PR DESCRIPTION
**Pull request by jeroenseegers**
Example nginx config added which can be used as contents of `/etc/nginx/sites-enabled/default`.

Closes #142 and #55.

### CODE REVIEW

**Comment by jeroenseegers** [comment]
When using this, be sure to have both nginx and php5-fpm installed.

```shell
sudo apt-get install nginx
sudo apt-get install php5-fpm
```

This configuration assumes default configuration for both of them.

**Comment by panique** [comment]
Thanks, this is fantastic !! :)

**Comment by jeroenseegers** [comment]
Hehe, glad you like it!

I'll probably throw together a second Vagrant install for use with nginx sometime later too.

**Comment by panique** [comment]
I'll merge this on the weekend btw (I'm not on my PC right now)

**Comment by panique** [comment]
THank you very much, very useful stuff! :)

**Pull request merged**
